name       : sfnt2woff-zopfli
version    : 1.1.0
release    : 1
source     :
    - https://github.com/bramstein/sfnt2woff-zopfli/archive/v1.1.0.tar.gz : 86deae57d0bd0eb395f2797c370613e62c1f33dd86626a21e309b154c98efa6b
license    :
    - Apache-2.0
    - MPL-1.1
component  : multimedia.graphics
summary    : WOFF utilities with Zopfli compression
description: |
    WOFF utilities with Zopfli compression
rundeps    :
    - zopfli
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/bin
    install -Dm00755 $workdir/{sfnt2woff,woff2sfnt}-zopfli $installdir/usr/bin/
